lib/Locale/Po4a/AsciiDoc.pm, t/data-30/TitlesUTF8.asciidoc, t/data-30/TitlesUTF8.po
Asciidoctor requires that title markers be the same character
length as the title.  The original code counted length in ASCII
characters, without regard to Unicode.  Therefore double-character
languages got too many markers.  This patch uses the chars method
instead of the columns method
t/30 was amended to include Japanese double-width characters
=> Properly insert AsciiDoc title markers

lib/Locale/Po4a/AsciiDoc.pm
Directives, such as include:: often have empty attribute lists
=> Allow empty AsciiDoc Attribute lists

Build.PL, Po4aBuilder.pm
As for Module::Build  [docs](https://github.com/Perl-Toolchain-Gang/Module-Build/blob/master/lib/Module/Build/API.pod)
> recommends
...
If a module is recommended but not required, all tests should still pass if the module isn't installed. This may mean that some tests may be skipped if recommended dependencies aren't present.
But as for now the tests for sgml and ascidoc fail if Sgml and GCString are not installed respectively.
So I suggest those modules should also go to test_requires.
=> Build.PL: add test_requires entry

doc/po4a.7.pod
Current documentation makes think that KernelHelp messages of only exact =2.4.x kernels are handled
and recent versions may not, this commit changes it a bit.
=> po4a.pod: minor fix to description of KernelHelp

lib/Locale/Po4a/AsciiDoc.pm
We allow empty attribute lists, the check does not and is unneeded
=> Remove check for invalid attribute lists

lib/Locale/Po4a/AsciiDoc.pm, t/data-30/StyleMacro.asciidoc, t/data-30/StyleMacro.out
Asciidoc macros with an empty target were not matched as being a macro.
An example of a macro with an emtpy target is `endif::[]`
Signed-off-by: Martijn Thé <post@martijnthe.nl>
=> bugfix: asciidoc: handle macros with empty target

lib/Locale/Po4a/Yaml.pm, t/data-32/yamlkeysoption1.po, t/data-32/yamlkeysoption2.po, t/data-32/yamltest.po, t/data-32/yamlutf8.po
This PR adds references from the yaml hierarchy.
I'll fix the tests if it passes review.
=> yaml: Add references

lib/Locale/Po4a/Yaml.pm, t/data-32/yamlkeysoption1.po, t/data-32/yamlkeysoption2.po, t/data-32/yamltest.po, t/data-32/yamlutf8.po
`//` is interpreted as `/` in UNIX path, so I'd prefer using `>` which doesn't have this convention.
```
-
-
- a
-
-
- b
```
```
#. type: Array Element
#: >>
#, no-wrap
msgid "a"
msgstr ""
#. type: Array Element
#: >>
#, no-wrap
msgid "b"
msgstr ""
```
=> yaml: Use ">" instead in references

lib/Locale/Po4a/AsciiDoc.pm, t/t-03-asciidoc/Lists.asciidoc, t/t-03-asciidoc/Lists.err, t/t-03-asciidoc/Lists.out, t/t-03-asciidoc/Lists.pot
Lists are not required to be indented.  This fixes them to put separate items in the .pot file
=> Fix Asciidoc unindented lists

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/03-asciidoc.t, t/t-03-asciidoc/Tables.asciidoc, t/t-03-asciidoc/Tables.out, t/t-03-asciidoc/Tables.pot
Table formats have changed.  The old formats are deprecated
and parsed by neither asciidoc or asciidoctor.
Treating tables as no-wrap passes them as preserved
Tentative fix for #61 - do not merge yet
=> Make Tables a no-wrap output in AsciiDoc

NEWS, doc/po4a.7.pod, lib/Locale/Po4a/Dia.pm, lib/Locale/Po4a/Docbook.pm, lib/Locale/Po4a/Guide.pm, lib/Locale/Po4a/InProgress/Debconf.pm, lib/Locale/Po4a/InProgress/NewsDebian.pm, lib/Locale/Po4a/Sgml.pm, lib/Locale/Po4a/TransTractor.pm, lib/Locale/Po4a/Wml.pm, lib/Locale/Po4a/Xhtml.pm, lib/Locale/Po4a/Xml.pm, po4a, t/02-addendums.t, t/t-02-addendums/article.addendum1, t/t-02-addendums/article.conf, t/t-02-addendums/article.ja.xml-good, t/t-02-addendums/article.po.ja, t/t-02-addendums/article.xml, t/t-02-addendums/book-auto.ja.xml-good, t/t-02-addendums/book-auto.xml, t/t-02-addendums/book-potin.conf, t/t-02-addendums/book.addendum1, t/t-02-addendums/book.conf, t/t-02-addendums/book.ja.xml-good, t/t-02-addendums/book.po.ja, t/t-02-addendums/book.po.ja-good, t/t-02-addendums/book.xml, t/t-05-config/test07.err
Since #148 was auto closed, I am creating new merge request.
This has much cleaner history... I hope you can accept this one.
=> enhance debug output, fix docbook behavior, allow separate input for POT

lib/Locale/Po4a/AsciiDoc.pm, t/t-03-asciidoc/Tables.pot
This is the previous behavior and it should be preserved at least.
=> asciidoc: do not include table fences in pot

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/03-asciidoc.t, t/t-03-asciidoc/NoImageTarget.asciidoc, t/t-03-asciidoc/NoImageTarget.out, t/t-03-asciidoc/NoImageTarget.pot
Most of the time, the images are relative to the asciidoc files and
don't need special processing. This option does not change the default
behavior, so that existing projects are not broken.
=> asciidoc: add option to prevent translation of image targets

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/03-asciidoc.t, t/t-03-asciidoc/TablesCells.asciidoc, t/t-03-asciidoc/TablesCells.out, t/t-03-asciidoc/TablesCells.pot
For test and comment :+1: 
This PR introduces the management of table cells in asciidoc. The support for now is very basic and has some known limitations:
* escaped  | are not managed. I couldn't come up with a correct regexp which would reject them. Maybe they can be managed later.
* for cells that contain asciidoc block formatting ("a|" cells), the content is processed as a verbatim block. The general rule is that if a cell content spans on two lines or more, the text is treated as verbatim.
Both limitations may be released in the future. They are less prioritary because making complex stuff in tables is generally discouraged or thrown upon: this usually a smell that a table is used for formatting purpose and not for presentation of tabular data.
This behavior breaks the previous one, …
=> [asciidoc] add basic table cells support

lib/Locale/Po4a/AsciiDoc.pm
For some reason, the content of a cell may be null.
=> asciidoc: do not crash if cell is nothing

NEWS, lib/Locale/Po4a/Text.pm, t/t-20-text/PandocYamlFrontMatter.po, t/t-20-text/PandocYamlFrontMatter.pot, t/t-20-text/PandocYamlFrontMatter.trans.po
Thanks to @mquinson's great work in 111e2281f92e3e39df0c768ba6b90d7a45aedc5e, po4a now supports Markdown with YAML Front Matter #196!  This pull request is a collection of small fixes to make things work smoothly with the standards. 
*  do not add trailing whitespace to YAML Front Matter PO comments
* YAML Front Matter is the widespread standard name for this block
* support YAML "end of document" tag 
More detail in the commit messages.
=> YAML Front Matter fixups

NEWS, lib/Locale/Po4a/Po.pm, po4a, t/t-05-config/test02.conf
This lets the `Language:` header be set in the .pot file to declare what the source string language is.  This is not required nor apparently common, but it doesn't break how _gettext_ works: https://lists.gnu.org/archive/html/bug-gettext/2020-04/msg00004.html
=> po4a: Use value of --master-language for the language of the generated POT file

lib/Locale/Po4a/Po.pm, lib/Locale/Po4a/Text.pm, lib/Locale/Po4a/TransTractor.pm, t/t-20-text/MarkDown.pot, t/t-20-text/MarkDownNestedLists.pot, t/t-20-text/MarkDownNoWrap.pot, t/t-20-text/MarkDownRules.pot, t/t-20-text/MarkDownYamlFrontMatter.pot, t/t-20-text/MarkDownYamlFrontMatter.trans.po, t/t-20-text/MarkDownYamlFrontMatterOptions.pot, t/t-20-text/PandocHeaderMultipleLines.pot, t/t-20-text/PandocMultipleAuthors.pot, t/t-20-text/PandocOnlyAuthor.pot, t/t-20-text/PandocOnlyTitle.pot, t/t-20-text/PandocTitleAndDate.pot, t/t-20-text/PandocTitleAuthors.pot
_gettext_ defines many flags for various entries that need special handling: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html  Markdown text is such a thing.  Translation tools like Weblate will automatically enable certain checks and displays based on the _gettext_ flags.  This change defines a new flag `markdown-text` to make all text entries that can have Markdown syntax in them.
(FYI, Weblate currently uses `md-text` but we're adding `markdown-text` since much less ambiguous.  The built-in _gettext_ flags do not use abbreviations.  Follow that here https://github.com/WeblateOrg/weblate/issues/3648)
=> add gettext flag "markdown-text" for relevant entries

lib/Locale/Po4a/AsciiDoc.pm, t/t-03-asciidoc/Lists.asciidoc, t/t-03-asciidoc/Lists.out, t/t-03-asciidoc/Lists.pot
This is accepted in the specification of asciidoc.
fixes #210
=> asciidoc: accept lines beginning 3 dots as numbered list items

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/t-03-asciidoc/Lists.asciidoc, t/t-03-asciidoc/Lists.out, t/t-03-asciidoc/Lists.pot
The limitation to 5 levels has been lifted in
https://github.com/asciidoctor/asciidoctor/issues/2854
=> asciidoc: accept nested number list of any depth

lib/Locale/Po4a/Xml.pm
Add a description for a missing option 'regex' for the get_string_until() function.
=> Xml.pm: a minor documentation enhancement

t/Testhelper.pm
The value of 'Project-Id-Version' depends on the root directory of po4a.
=> Fix tests that use msginit

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/fmt-asciidoc.t
Empty lines in tables managed as blocks must be passed "as is".
Fixes #226
=> asciidoc: correctly manage empty lines in tables

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/fmt/asciidoc/Titles.adoc, t/fmt/asciidoc/Titles.norm, t/fmt/asciidoc/Titles.norm.stderr, t/fmt/asciidoc/Titles.po, t/fmt/asciidoc/Titles.pot, t/fmt/asciidoc/Titles.trans, t/fmt/asciidoc/Titles.trans.stderr
Two lines titles are tolerant wrt to underline length (±2 chars of
title length). The spec stipulates that the underline's length must be
even but this is not checked here.
Fixes #212
=> asciidoc: tolerate underline length variations in two lines titles

po4a
This fixes several issues with the --srcdir handling so that it does the right thing. These were causing build failures in at least dpkg and aptitude. I've also checked all other instances of find_output_file and they look ok, but a second look would make sense anyway. :)
Fixes Debian bug #960892.
=> Fix --srcdir handling

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/fmt-asciidoc.t, t/fmt/asciidoc/StrictDelimitedBlocks.adoc, t/fmt/asciidoc/StrictDelimitedBlocks.norm, t/fmt/asciidoc/StrictDelimitedBlocks.po, t/fmt/asciidoc/StrictDelimitedBlocks.pot, t/fmt/asciidoc/StrictDelimitedBlocks.trans
If a block contains a line of the same kind of characters but of
different length, this line is interpreted as a closing fence, just
like python asciidoc.
This is an issue because this means that no such line can be included
in a block. Asciidoctor solves that issue by requiring the opening and
closing fences to be the same length, which can be chosen arbitrarily
greater than 3.
The strict option makes the same test.
Fixes #239
=> asciidoc: strict option to match strictly equal block fences

CONTRIBUTING.md, META.json, NEWS, lib/Locale/Po4a/TransTractor.pm
Release 0.62 and instructions for openSUSE Leap
=> Release 0.62

NEWS, lib/Locale/Po4a/Yaml.pm, t/cfg-split.t, t/cfg/split-yaml/_index.md, t/cfg/split-yaml/_index.vi.md, t/cfg/split-yaml/_output, t/cfg/split-yaml/content.pot, t/cfg/split-yaml/content.vi.po, t/cfg/split-yaml/en.yaml, t/cfg/split-yaml/i18n.pot, t/cfg/split-yaml/i18n.vi.po, t/cfg/split-yaml/po4a.cfg, t/cfg/split-yaml/vi.yaml, t/fmt/yaml/basic.po, t/fmt/yaml/basic.pot, t/fmt/yaml/keysoption1.po, t/fmt/yaml/keysoption1.pot, t/fmt/yaml/keysoption2.po, t/fmt/yaml/keysoption2.pot, t/fmt/yaml/skiparray.po, t/fmt/yaml/utf8.po, t/fmt/yaml/utf8.pot
- Fix #289
Instead of key names, use the file name and line number 0 as the reference. Put key names in the comment for type
- Add a test for the case of split settings with an YAML master doc
=> Make the Yaml module follow the reference style of YAML Front Matter in Markdown module

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/fmt/asciidoc/StyleMacro.adoc, t/fmt/asciidoc/StyleMacro.norm, t/fmt/asciidoc/StyleMacro.pot, t/fmt/asciidoc/StyleMacro.trans
Issue summary:
```
```
More details in the [maillist post](https://lists.po4a.org/archives/list/devel@lists.po4a.org/thread/NZLXESHZKXCCRM2G2IX7OALS4V2WGVPI/).
First PR here, I'll need someone to review please.
Thanks!
=> Asciidoc: Don't split in attributes include:: and ifeval:: lines

NEWS, lib/Locale/Po4a/Po.pm
This change mitigates #302 when perl exhibits the bug
https://github.com/Perl/perl5/issues/18604
and seems to speed up flag matching.
fix #302
=> Instead of using a regex, use subsbtring matching for flags

lib/Locale/Po4a/Yaml.pm, po/bin/po4a.pot, t/fmt-yaml.t, t/fmt/yaml/keysandpaths1.po, t/fmt/yaml/keysandpaths1.pot, t/fmt/yaml/keysandpaths1.trans, t/fmt/yaml/pathsoption1.po, t/fmt/yaml/pathsoption1.pot, t/fmt/yaml/pathsoption1.trans
I have the need to filter which specific paths should be extracted from my Yaml files, not only on the key name.
To stay backwards compatible I didn't modify the handling of the `keys` parameter, but instead introduced a new one.
Example:
`/usr/src/po4a/po4a-gettextize -d -f yaml -m en/antora-playbook.yml -o paths="site title,site url,asciidoc attributes idseparator" -o keys="url" -o skip_array`
This would include **all** keys named `url` and additionally the specific elements addressed by the paths:
```yaml
site:
title: User Manual
url: https://manual.example.com/en
start_page: index.adoc
content:
sources:
- url: ..
branches: HEAD
start_path: en/
ui:
bundle:
url: https://files.example.com/ui-bundle-release.zip
snapshot: true
asciidoc:
attributes:
idprefix: ""
idseparator: "-" …
```
=> [Yaml] add option to parse only specific Yaml paths

lib/Locale/Po4a/Xhtml.pm, t/fmt-xhtml.t, t/fmt/xhtml/table.html, t/fmt/xhtml/table.norm, t/fmt/xhtml/table.po, t/fmt/xhtml/table.pot, t/fmt/xhtml/table.trans
The Xhtml documentation indicate that table support is not present
as it is not tested.  Tables seem to work, so lets add a test
and remove the documentation comment.
=> Add new xhtml table test and stop claiming tables are not tested

Po4aBuilder.pm
Since the manpages are generated at build time, and gzip by
default includes the file timestamp in the compressed file,
this 'leaks' the build time into the resulting artifact.
There are many advantages to avoiding 'leaking' the build time
into the artifact: it can make detecting compromised CI servers
easier through https://reproducible-builds.org/ , can make
content-addressed storage more effective and improve cache hits
when rebuilding.
=> Avoid embedding the build date in compressed manpages

lib/Locale/Po4a/TransTractor.pm
Update to TransTractor.pm in order to avoid quotes being added around boolean values (true/false) in YAML and MarkDown front matter. If quotes are added the values are treated as strings rather than as booleans.
=> do not quote booleans in YAML

lib/Locale/Po4a/TeX.pm
Previously, a trailing space was matched by \s+, but this is counter-intuitive, and couldn't make it work before digging in the code.
Match the behavior of non-verbatim environment by making it \s* (allowing, but not requiring trailing spaces).
=> TeX.pm: allow verbatim environment declaration without trailing space

NEWS, lib/Locale/Po4a/Text.pm, t/fmt/txt-markdown/Basic.md, t/fmt/txt-markdown/Basic.norm, t/fmt/txt-markdown/Basic.po, t/fmt/txt-markdown/Basic.pot, t/fmt/txt-markdown/Basic.trans
This pull request marks link reference definitions in the markdown document as no-wrap, which avoids unintentional line breaks at the colon in the long link reference definition line.
Here are some limitations below, but I suspect it works in most cases:
* Multiline link reference definition is not supported ([Example 193](https://spec.commonmark.org/0.30/#example-193))
* It misinterprets a link reference definition if its link text is invalid ([Example 197](https://spec.commonmark.org/0.30/#example-197))
* Link reference definition may interrupt normal paragraph ([Example 213](https://spec.commonmark.org/0.30/#example-213))
=> markdown: support link reference

lib/Locale/Po4a/Texinfo.pm, t/fmt-texinfo.t, t/fmt/texinfo/partialmenus.norm, t/fmt/texinfo/partialmenus.po, t/fmt/texinfo/partialmenus.pot, t/fmt/texinfo/partialmenus.texi, t/fmt/texinfo/partialmenus.trans
Fixes <https://issues.guix.gnu.org/64881>.
* lib/Locale/Po4a/Texinfo.pm (translate_buffer_menuentry): Refine regexp, so that it matches menu entries lacking a description. Only call 'translate_buffer' on the description if it was provided.
* t/fmt/texinfo/partialmenus.trans: New file.
* t/fmt/texinfo/partialmenus.texi: Likewise.
* t/fmt/texinfo/partialmenus.pot: Likewise.
* t/fmt/texinfo/partialmenus.po: Likewise.
* t/fmt/texinfo/partialmenus.norm: Likewise.
* t/fmt-texinfo.t: Register the new 'partialmenus' test.
=> lib: Texinfo: Translate partial menu node names.

lib/Locale/Po4a/Sgml.pm
This were confusing po4a into thinking the previous paragraph were verbatim
=> Sgml: remove stray space from the doc

CONTRIBUTING.md, po/pod/ca.po, po/pod/de.po, po/pod/eo.po, po/pod/es.po, po/pod/fr.po, po/pod/hr.po, po/pod/hu.po, po/pod/it.po, po/pod/ja.po, po/pod/nb.po, po/pod/nl.po, po/pod/pl.po, po/pod/po4a-pod.pot, po/pod/pt.po, po/pod/pt_BR.po, po/pod/ru.po, po/pod/sr_Cyrl.po, po/pod/uk.po, po/pod/zh_Hans.po, po/pod/zh_Hant.po, po4a-normalize
This is useful to create tests.
Also this PR:
- fixes a typo in the description of the neighbouring option and untypos the PO-files.
- updates "Writing a test" section in CONTRIBUTING.md
=> po4a-normalize: add an option to create capitalized version of documenе

lib/Locale/Po4a/TeX.pm
Fix mquinson/po4a#521
Using \input instruction in TeX file results in error "No such file or directory"
becouse kpsewhich return wrong filename.
This PR fix it.
=> TeX: Fix error read input/include file

t/fmt-tex.t, t/fmt/tex/input-in-basic.norm, t/fmt/tex/input-in-basic.po, t/fmt/tex/input-in-basic.pot, t/fmt/tex/input-in-basic.tex, t/fmt/tex/input-in-basic.trans, t/fmt/tex/subtext.tex
Fix mquinson/po4a#521
Existing tests check invalid input command (included file not exist) and not check valid input command (included file exist and must be include). This PR fix it.
=> TeX: Add format test for valid input command

NEWS, README.md, doc/po4a.7.pod, lib/Locale/Po4a/Chooser.pm, lib/Locale/Po4a/Org.pm, po/pod.cfg, t/fmt-org.t, t/fmt/org/basic.norm, t/fmt/org/basic.org, t/fmt/org/basic.po, t/fmt/org/basic.pot, t/fmt/org/basic.trans
Hello,
This is a new module for the Org format, which is typically used in [the Org mode][org].
I have used this module to translate some of their documents (such as the [Org Mode Compact Guide][guide]), and it seems to work.
~~This also adds some links to the Gemtext module (#466).~~ I'll make another pull request.
Thank you,
gemmaro.
- - -
TODO:
It is useful for manipulating lists, but as more dependencies are added, the packaging will need to be updated.
There are places where $ref and $type are missed or extra passed.
These tasks are future work:
- Conform to [the Org Syntax](https://orgmode.org/worg/org-syntax.html)
- Improved parser when targeting the Org reference manual.
[org]: https://orgmode.org/
[guide]: https://orgmode.org/guide/
=> New module for Org format

lib/Locale/Po4a/TeX.pm
Previously, the closing brace `}` would be matched as part of the filename, which was then not found.
This allows the use of `\input` commands as macro parameters, for instance with the `\subcaptionbox` command:
```tex
\subcaptionbox{Legend}[2cm]{\input{sometikzplot.tex}}
```
Fixes #405
=> TeX.pm: allow \input command surrounded by curly braces

NEWS, lib/Locale/Po4a/Man.pm, lib/Locale/Po4a/Po.pm, lib/Locale/Po4a/TransTractor.pm
This removes DynaLoader from some is-a relationships.
DynaLoader was introduced in 0a4e526ddd3a3a5e9cc92f1832833d21a37b314c, but was removed in dbbc6d2c763ce89a13af003871ecffa01a8edc30 long time ago.  So it should be safe to remove it now.
=> Remove DynaLoader

lib/Locale/Po4a/Texinfo.pm
This effectively fixes issues reported in #497. The document remains correct after translation and `texi2any` doesn't report any errors.
PS: Some issues still remain like there are some instances of incorrect paragraph splitting e.g. it's assumed that `@item` entry last only one line rather than for a whole paragraph.
=> Texinfo: some improvements

NEWS, po4a, t/cfg-args.t, t/cfg/args-global/_output-target-lang
This option should allow to transition to po4a from po4a-*, while retaining the same steps in makefiles
=> add --target-lang option to po4a

po4a-translate
As po4a-translate doesn't have such an option.
=> po4a-translate: remove --porefs option from docs

po4a
Writing the same file changes the timestamp, which is not good for use in Makefile dependencies. This commit avoids writing a doc file if the content has not changed from what is already in the file.
=> Do not touch a doc file if it has not changed

t/Testhelper.pm
This pull request addresses an issue with the test helper by ensuring that the options for `po4a-updatepo` do not include the `--width=<width>` option. This change may be related to commit faa7bc81720e7c3c5427d0bbde8c14998dd62934.
=> Fix test helper to exclude `--width` option from `po4a-updatepo` options

.github/workflows/linux.yml, Containerfile
Can be used to test po4a during development or when released.
The main motivation here is to simplify building the website since it requires built sources. This way website updates could be automated instead of the current manual process and then published via OpenShift.
The website deployment (aside from building and publishing the content) is done via Ansibel by RH OSPO and here is the corresponding change to switch to OpenShift: https://gitlab.com/osci/community-cage-infra-ansible/-/merge_requests/717
This requires a change in a role to deploy PHP on Openshift: https://gitlab.com/osci/ansible-role-openshift-apps/-/merge_requests/43
This role cannot use a lightweight web server in this case because the way Apache handles language file extensions (*.php.<lang>) in the original website …
=> Publish test container images

.github/workflows/linux.yml
PRs from external contributors are not allowed to push in the registry.
=> ci: fix CI for PRs

.tidyallrc, Build.PL, Containerfile, Po4aBuilder.pm
Hello,
This update introduces two minor improvements to the DocBook document-to-manpage conversion process:
1. Expanded file path detection to include the `file:/path/to/XSLT/file` format alongside the existing `file:///path/to/XSLT/file` format (e.g. `file:/gnu/store/.../manpages/docbook.xsl` with GNU Guix).
2. Utilization of the `IPC::Open3` module for invoking the `xmlcatalog` command, ensuring a more secure method for retrieving the XSLT file path in Perl scripts.
Thank you.
=> Enhance DocBook document-to-manpage conversion process

lib/Locale/Po4a/VimHelp.pm, t/fmt/vimhelp/basic.norm.stderr, t/fmt/vimhelp/basic.trans.stderr
The `textwidth` option has been removed from the VimHelp module due to the complexity involved in achieving the desired behavior efficiently and effectively.  While initially intended to enhance functionality, its implementation presented challenges that made it impractical to retain under reasonable conditions.
Partially addresses #551.
=> Remove textwidth option of VimHelp module

.dir-locals.el
This specifies a project-specific bug reference pattern and URL formats.
This allows bug tracker links to be highlightened, especially when the Emacs's bug-reference minor mode is enabled for the NEWS file, for instance.
Other project which has its own `.dir-locals.el` file: <https://git.savannah.gnu.org/cgit/guix.git/tree/.dir-locals.el>
=> Add support for Emacs bug-reference mode

.tidyallrc
This might be specific to my environment, but removing this option seems to prevent garbled characters in files when running TidyAll.
=> Remove UTF-8 flag for PerlTidy in TidyAll config file.

doc/addendum.ca, doc/addendum.es, doc/addendum.fr, doc/addendum.it, doc/addendum.ja, doc/addendum.pl, doc/addendum.pt_BR, doc/addendum.zh_Hans, lib/Locale/Po4a/SimplePod.pm, lib/Locale/Po4a/SimplePod/Parser.pm, po/pod.cfg
This is a continuation of #573 with the following updates:
- Fixes `ref` values in PO files to use proper `refname`s instead of full file paths.
- Switches our po4a processing POD manuals to use the SimplePod module.
- Updates addendum files accordingly.
=> Switch to SimplePod for po4a documents and fix reference handling

lib/Locale/Po4a/TeX.pm
The heading text is not "WRITING DERIVATIVE MODULES"
=> Fix heading text mention in TeX.pm

lib/Locale/Po4a/Man.pm, t/fmt/man/quotes.man, t/fmt/man/quotes.norm, t/fmt/man/quotes.po, t/fmt/man/quotes.pot, t/fmt/man/quotes.trans
Namely do `s/\\&"/\\(dq/` only until after we handle all the quotes that might separate commands' arguments.
Closes: https://github.com/mquinson/po4a/issues/445
=> man: fix po4a's incorrect handling of \& in doblequotes

Po4aBuilder.pm
`use strict` is redundant after `use v5.16.0` (`use`ing any perl version after 5.12 automatically enables strict: https://perldoc.perl.org/perl5120delta#Implicit-strictures).
Also, explicitly spell v-strings with a leading `v` because while `use 5.16.0`, `use v5.16.0`, and `use v5.16` will all do what you want, `use 5.16` will require version 5.160 of perl. So I generally prefer the belt-and-suspenders approach of specifying both `v` and a 3-part number.
=> Po4aBuilder: remove redundant 'use strict'

Po4aBuilder.pm, t/fmt-docbook.t
See:
https://perl-begin.org/tutorials/bad-elements/#non_explicitly_imported_symbols
=> Avoid implicit perl imports - make them explicit.

lib/Locale/Po4a/Po.pm, po4a, po4a-updatepo
Some typos found when translating po4a-doc. Please let me know if using the squash option in the merge button ia not an option.
=> Fix typos in the docs
