lib/Locale/Po4a/Xml.pm
Contributed by Ineiev, thanks.
=> Add an option to not wrap attributes

doc/po4a.7.pod
Note that the second patch need a review...
=> A couple more enhancements for po4a(7)

MANIFEST, lib/Locale/Po4a/Text.pm, t/31-text.t, t/data-31/KeyValue.err, t/data-31/KeyValue.out, t/data-31/KeyValue.po, t/data-31/KeyValue.text
Fixes #8
Signed-off-by: Brian (bex) Exelbierd <bex@pobox.com>
=> Add keyvalue option to not wrap key:value paras

lib/Locale/Po4a/Debconf.pm, lib/Locale/Po4a/Html.pm, lib/Locale/Po4a/NewsDebian.pm, lib/Locale/Po4a/Wml.pm, lib/Locale/Po4a/Xhtml.pm
=> Update FSF address

README, lib/Locale/Po4a/Chooser.pm, lib/Locale/Po4a/Yaml.pm, t/32-yaml.t, t/data-32/yamlkeysoption1.out, t/data-32/yamlkeysoption1.po, t/data-32/yamlkeysoption1.yaml, t/data-32/yamlkeysoption2.out, t/data-32/yamlkeysoption2.po, t/data-32/yamlkeysoption2.yaml, t/data-32/yamltest.out, t/data-32/yamltest.po, t/data-32/yamltest.yaml
This implements YAML parsing with YAML::Tiny
=> Add YAML file support

doc/po4a.7.pod, lib/Locale/Po4a/Common.pm, lib/Locale/Po4a/Halibut.pm, lib/Locale/Po4a/Man.pm, lib/Locale/Po4a/TeX.pm, lib/Locale/Po4a/TransTractor.pm, po4a, po4a-translate, po4a-updatepo, scripts/msguntypot
Many thanks for fixing these typos and keeping docs up-to-date.
=> Fix minor typos

po4a
Prevent the translated files from being remove if the keep threshold isn't met.
=> Keep the old translation files if the keep threshold isn't met.

lib/Locale/Po4a/Text.pm, t/33-fortunes.t, t/data-33/MultipleLines.out, t/data-33/MultipleLines.po, t/data-33/MultipleLines.txt, t/data-33/SeveralFortunes.out, t/data-33/SeveralFortunes.po, t/data-33/SeveralFortunes.txt, t/data-33/SingleFortune.out, t/data-33/SingleFortune.po, t/data-33/SingleFortune.txt
Hi Martin,
this should fix Debian bug #900649.
Regards,
Tobias
=> Fix for fortunes parsing

lib/Locale/Po4a/Text.pm, t/data-33/MultipleLines.out, t/data-33/MultipleLines.po, t/data-33/MultipleLines.txt
Hi Martin,
I've reorganized the code for the fortunes parsing, it still passes :-) You might want to merge this as well.
As I'm fairly new to the po4a codebase: Is there a method to detect the end of file? Or is it the only way as I've done it in the code to shift the next line and see if it's defined?
Regards,
Tobias
=> Code cleanup for fortunes parsing

NEWS
Hi Martin,
I'm not sure if the change is important enough to be mentioned in the NEWS. If you think it should be mentioned, this would be my suggestion.
Regards,
Tobias
=> Mention changed handling of fortunes

NEWS, lib/Locale/Po4a/Man.pm, t/23-man.t, t/data-23/macros.1, t/data-23/macros.de.1, t/data-23/macros.de.po, t/data-23/macros.pot
Hi Martin,
the most part of this pull request is about adding support for three new macros. Some unrelated minor changes are also included, for example the missing NEWS item for .ME macros and some typo fixes.
Regards,
Tobias
=> Support command synopsis macros

Build.PL
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Make sure Pod::Parser is installed to avoid issue 142

CONTRIBUTING.md
This adds a note about the NEWS file I keep forgetting about :)
=> Add PR section, including NEWS note

lib/Locale/Po4a/Text.pm, t/t-20-text/PandocFencedCodeBlocks.out, t/t-20-text/PandocFencedCodeBlocks.pot
=> Not to append unnecessary newline characters

lib/Locale/Po4a/Xml.pm, po4a-updatepo
[source](https://hosted.weblate.org/projects/po4a/po4a/source/review/?type=check%3Aellipsis)
=> ellipsis, added

CONTRIBUTING.md, README.md
Fixed the grammatical errors in readme and contributing file.
=> Fixed the grammatical errors.

po4a
Add B<>-style empasis to a referenced option inside --keep-translation description.
=> po4a: minor documentation emphasis improvement

doc/po4a.7.pod, po4a, po4a-gettextize
@mquinson I read through the doc file changes and made some grammar / voice suggestions.  To meet the needs of the format, the text got reflowed.  Feel free to accept/reject as you see fit.
=> Update new docs with grammar and voice fixes

lib/Locale/Po4a/Text.pm, t/fmt-txt-markdown.t, t/fmt/txt-markdown/NestedLists.po, t/fmt/txt-markdown/NestedLists.pot, t/fmt/txt-markdown/NestedLists.trans
=> Locale::Po4a::Text: supported nested lists

lib/Locale/Po4a/Po.pm
Thanks in advance for reviewing.
=> Translate more messages

lib/Locale/Po4a/Texinfo.pm, t/fmt-texinfo.t, t/fmt/texinfo/tindex.norm, t/fmt/texinfo/tindex.po, t/fmt/texinfo/tindex.pot, t/fmt/texinfo/tindex.texi, t/fmt/texinfo/tindex.trans
Added support for `@tindex` command. It includes a test for it.
=> Texinfo: add @tindex support

Po4aBuilder.pm
=> Fix Po4aBuilder to use -I instead of reseting PERL5LIB

README.md, doc/po4a.7.pod, lib/Locale/Po4a/KernelHelp.pm
Also delete erroneous comment in KernelHelp module
=> Update documentation for module list

NEWS, lib/Locale/Po4a/AsciiDoc.pm
=> asciidoc: add nolinting option to remove linting messages

t/fmt/sgml/attributes-order.norm, t/fmt/sgml/attributes-order.po, t/fmt/sgml/attributes-order.pot, t/fmt/sgml/attributes-order.sgml, t/fmt/sgml/attributes-order.trans, t/fmt/sgml/basic.norm, t/fmt/sgml/basic.po, t/fmt/sgml/basic.pot, t/fmt/sgml/basic.sgml, t/fmt/sgml/basic.trans
by making the input sgml files valid docbook documents
wrt the stricter docbook sgml declaration.
This is also in contribution to #327 and fixes it.
Please review and test. I hope I didn’t patch out anything important that
the test was supposed to check, but I don’t think so. ;)
It works now on my system using the original `docbook.dcl` sgml declaration.
closes #327
=> Fix sgml tests

NEWS, lib/Locale/Po4a/AsciiDoc.pm, t/fmt-asciidoc.t, t/fmt/asciidoc/MacroIncludesHugo.adoc, t/fmt/asciidoc/MacroIncludesHugo.norm, t/fmt/asciidoc/MacroIncludesHugo.po, t/fmt/asciidoc/MacroIncludesHugo.pot, t/fmt/asciidoc/MacroIncludesHugo.trans
=> asciidoc: Support Hugo shortcode on macros

lib/Locale/Po4a/Xml.pm
Resolves the issues #389 and #391.
This fix can
- treat placeholder for empty elements, and
- translate attributes inside attribute-folded inline and placeholder.
In order to realize former feature,
- extracted special processes for open and close tags in `treat_content` and put into `treat_content_open_tag` and `treat_content_close_tag` respectively,
- applied both `treat_content_open_tag` and `treat_content_close_tag` for empty-element tag in `treat_content`, and
- disabled tag breaking for placeholder-marked empty-element tag in `tag_break_alone`.
In order to realize latter feature, when processing open tag marked as placeholder or attribute-folded, passed the tag into `treat_attributes`.
=> Improved XML inline-related translation features

.github/workflows/linux.yml
Signed-off-by: Jean-Noël Avila <jn.avila@free.fr>
=> Fix linux github action

README.md, po4a, po4a-gettextize, po4a-normalize, po4a-translate, po4a-updatepo
Updated all copyright note dates
=> Updated all copyright dates

lib/Locale/Po4a/Sgml.pm
=> SGML: replace invalid byte (0xa0) in comment with space (0x20)

.tidyallrc, NEWS, Po4aBuilder.pm
=> Use xmlcatalog to find DocBook XSL file

doc/po4a.7.pod
po4a has been central to how we maintain our docs so thought I'd add our project to the list.
=> Add project to list

MANIFEST, po/pod/zh_Hans.po, po/pod/zh_Hant.po
zh_CHS to zh_Hans
zh_CHT to zh_Hant
Fix #419
This caused an error in debiman so came here to fix it.
=> Fix Chinese lang codes

po4a-gettextize
=> po4a-gettextize: Some small typo fixes in documentation

po4a
probably those should be merged after the release to not mess up translations.
=> po4a: Some small typo fixes in documentation

po4a
I think that this is trivial and should be done after the release as it will cause the PO file to be updated.
=> Fix Japanese language code from jp to ja

doc/po4a.7.pod, lib/Locale/Po4a/AsciiDoc.pm, lib/Locale/Po4a/Halibut.pm, lib/Locale/Po4a/LaTeX.pm, lib/Locale/Po4a/Po.pm, lib/Locale/Po4a/Pod.pm, lib/Locale/Po4a/Sgml.pm, lib/Locale/Po4a/Texinfo.pm, lib/Locale/Po4a/Text.pm, lib/Locale/Po4a/Yaml.pm, po4a-updatepo
Mostly formatting enhancements and punctuation fixes, but also some rewording of more obscure paragraphs.
=> Several more fixes to docs

README.md, doc/po4a.7.pod, lib/Locale/Po4a/Chooser.pm, po/pod.cfg
=> Add Gemtext module entry to some documentation

t/fmt-tex.t, t/fmt/tex/input-merge-basic-surrounded-curly-braces.norm, t/fmt/tex/input-merge-basic-surrounded-curly-braces.po, t/fmt/tex/input-merge-basic-surrounded-curly-braces.pot, t/fmt/tex/input-merge-basic-surrounded-curly-braces.tex, t/fmt/tex/input-merge-basic-surrounded-curly-braces.trans
=> TeX: Add format test for input command surrounded curly braces

lib/Locale/Po4a/AsciiDoc.pm, lib/Locale/Po4a/Org.pm, lib/Locale/Po4a/Text.pm, po4a, scripts/msgsearch, scripts/po4a-display-pod, t/fmt/txt-markdown/PandocFencedCodeBlocks.md, t/fmt/txt-markdown/PandocFencedCodeBlocks.norm, t/fmt/txt-markdown/PandocFencedCodeBlocks.po, t/fmt/txt-markdown/PandocFencedCodeBlocks.pot, t/fmt/txt-markdown/PandocFencedCodeBlocks.trans
subj;
plus replace tabs with spaces all over the code base
Closes: https://github.com/mquinson/po4a/issues/546
=> markdown: avoid searching for bullets in code blocks

.envrc
This introduces a dotenv file (`.env`) and a Direnv configuration file (`.envrc`) for Perl development. Additionally, the `.envrc` file includes optional setup for Guix integration.
=> Add Direnv config file for Perl development

Po4aBuilder.pm
system(LIST) runs the given command directly without going through the shell (unlike system(STRING)). This avoids problems with shell meta-characters (like `&` or `(`) that would have to be quoted otherwise. (It's also a bit more efficient.)
=> Po4aBuilder: avoid shell form of system()

lib/Locale/Po4a/AsciiDoc.pm, t/fmt-asciidoc.t, t/fmt/asciidoc/IncludeInLists.adoc, t/fmt/asciidoc/IncludeInLists.norm, t/fmt/asciidoc/IncludeInLists.po, t/fmt/asciidoc/IncludeInLists.pot, t/fmt/asciidoc/IncludeInLists.trans
=> asciidoc: fix handling of include macro in lists
